package Interfaz;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ConexionBD.Conexion;
import ConexionBD.crudsql;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import Interfaz.Loging;

import classDAO.MaestroDAO;
import java.awt.TextField;
import javax.swing.JComboBox;
import java.util.Iterator;
import java.sql.SQLException;
import java.sql.ResultSet;

public class Maestro extends javax.swing.JFrame {
    
    
    private final Conexion CON;
    Statement ps;
    private ResultSet rs;
   
    public Maestro() {
        initComponents();
        setLocationRelativeTo(null);
        CON = Conexion.getInstacia();
        grado.enable(false);
        Gradofinal.enable(false);
        //listargrado(gradox);
        //listarD(horarios);
        listarIDal(idAlumnos);
        P1.enable(false);
        P2.enable(false);
        P3.enable(false);
        grado_grupo.enable(false);
        listarIDal2(IDXD);
        //CalificacionF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        DOCENTE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        grado = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaalaumnos = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        P3 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        id_cali = new javax.swing.JTextField();
        P2 = new javax.swing.JTextField();
        P1 = new javax.swing.JTextField();
        activar3 = new javax.swing.JButton();
        parciales = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        id_alu = new javax.swing.JTextField();
        IDXD = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Gradofinal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLACALI = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        id_cal2 = new javax.swing.JTextField();
        grado_grupo = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Añadir = new javax.swing.JButton();
        idAlumnos = new javax.swing.JComboBox();

        jTextField1.setText("jTextField1");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo4.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 63, -1, -1));

        jLabel9.setText("Grado y Grupo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, -1));
        jPanel2.add(DOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID_docente: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 90, -1));

        grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoActionPerformed(evt);
            }
        });
        jPanel2.add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 64, 116, -1));

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });
        jPanel2.add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel10.setText("Mostrar lista de alumnos");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 208, -1));

        tablaalaumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_alumno", "grado_grupo", "nombre", "direccion", "telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaalaumnos);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 427, 150));

        Salir.setText("Cerrar");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel2.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alumno.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 340, 100));

        jTabbedPane1.addTab("Lista de Alumnos", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ID calificaion:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 57, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel32.setText("Detalles de la calificaiones");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 250, 24));

        jButton15.setText("Limpiar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 301, -1, -1));
        jPanel1.add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 227, 60, -1));

        jButton16.setText("Agregar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 301, -1, -1));
        jPanel1.add(id_cali, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 54, 131, -1));
        jPanel1.add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 227, 60, -1));
        jPanel1.add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 227, 60, -1));

        activar3.setText("cerrar");
        activar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activar3ActionPerformed(evt);
            }
        });
        jPanel1.add(activar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 301, -1, -1));

        parciales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Parcial 1", "Parcial 2", "Parcial 3" }));
        parciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcialesActionPerformed(evt);
            }
        });
        jPanel1.add(parciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 129, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Parcial:");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo4.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 250, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo4.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo4.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 250, 180));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo4.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 180));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("id_alumno");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 103, 70, 20));
        jPanel1.add(id_alu, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 105, 129, -1));

        jPanel1.add(IDXD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, -1));

        jTabbedPane1.addTab("Calificacion", jPanel1);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Calificaciones del grupo:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 13, -1, -1));
        jPanel3.add(Gradofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 187, 102, -1));

        TABLACALI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_calificaciones", "id_alumno", "grado_grupo", "cali_final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TABLACALI);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, 456, 94));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Grado Y Grupo: ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ID_CALIFICACION");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("ID ALUMNO");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Grado Y Grupo: ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));
        jPanel3.add(id_cal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 39, 102, -1));
        jPanel3.add(grado_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 79, 102, -1));

        jButton6.setText("Mostrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 186, -1, -1));

        Añadir.setText("Guardar");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });
        jPanel3.add(Añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 38, -1, -1));

        jPanel3.add(idAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, -1));

        jTabbedPane1.addTab("Cali Final", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void listarIDal(JComboBox idalumnos){
        
            String sql = "select id_alumno from alumnos where grado_grupo='"+grado.getText()+"'";
        
            try{
                Connection Conexion = CON.conectar();
                ps=CON.conectar().createStatement();
                rs = ps.executeQuery(sql);
            
                idalumnos.removeAllItems();
                while(rs.next()){
                    idalumnos.addItem(rs.getString("id_alumno"));
                
                }
                Conexion.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }
    void listarIDal2(JComboBox IDXD){
        
            String sql = "select id_alumno from alumnos where grado_grupo='"+grado.getText()+"'";
        
            try{
                Connection Conexion = CON.conectar();
                ps=CON.conectar().createStatement();
                rs = ps.executeQuery(sql);
            
                IDXD.removeAllItems();
                while(rs.next()){
                    IDXD.addItem(rs.getString("id_alumno"));
                
                }
                Conexion.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }
    
    
    
    
    
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        AgCali();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        P1.setText("");
        P2.setText("");
        P3.setText("");
        id_cali.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Loging log = new Loging();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed
   
    classDAO.LoginDAO x = new classDAO.LoginDAO();
    void buscar(){
        
        String xx = DOCENTE.getText();
        if(x.validar("select grado_grupo from docente where id_docente='"+xx+"'")==false){
            JOptionPane.showMessageDialog(rootPane, "id docente incorrecto!");
        }else{
                String grado_grup=grado.getText();
                //String grado2 =Gradofinal.getText();
            try {
                String sql = "select grado_grupo from docente where id_docente='"+xx+"'";
                Connection Conexion = CON.conectar();
                ps=CON.conectar().createStatement();
                rs = ps.executeQuery(sql);
           
                while(rs.next()){
                    grado_grup  = rs.getString("grado_grupo");
                    //grado2= rs.getString("grado_grupo");
                }
                    grado.setText(grado_grup);
                    Gradofinal.setText(grado_grup);
                    grado_grupo.setText(grado_grup);
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error...");
            }
        }
        listarIDal(idAlumnos);  
        listarIDal2(IDXD);
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mostrarA();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoActionPerformed
        //grado.getText();
        //String sql ="select * from docente where grado_grupo ='"+grado+"'";
    }//GEN-LAST:event_gradoActionPerformed

    private void parcialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcialesActionPerformed
        String opcion =(String) parciales.getSelectedItem();
        
        if(opcion.equals("Parcial 1")){
            P1.enable(true);
            P2.enable(false);
            P3.enable(false);
        }
        if(opcion.equals("Parcial 2")){
            P1.enable(false); 
            P2.enable(true);                  
            P3.enable(false);
        }
        if(opcion.equals("Parcial 3")){
            P1.enable(false);
            P2.enable(false);
            P3.enable(true);
        }
        
        
        
    }//GEN-LAST:event_parcialesActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
       AgregarCali();
    }//GEN-LAST:event_AñadirActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CalificacionF();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        buscar();
    }//GEN-LAST:event_BUSCARActionPerformed

    private void activar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activar3ActionPerformed
        Loging log = new Loging();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_activar3ActionPerformed
    DefaultTableModel modelALU;
    public void mostrarA(){
        String Grado = grado.getText();
        //
        String sql ="select * from alumnos where grado_grupo ='"+Grado+"'";
        try {
            Connection Conexion = CON.conectar();
            ps=CON.conectar().createStatement();
            rs = ps.executeQuery(sql);
            Object [] alumnos1 = new Object[5];
            modelALU = (DefaultTableModel) tablaalaumnos.getModel();
            while(rs.next()){
                alumnos1 [0] = rs.getString("id_alumno");
                alumnos1 [1] = rs.getString("grado_grupo");
                alumnos1 [2] = rs.getString("nombre");
                alumnos1 [3] = rs.getString("direccion");
                alumnos1 [4] = rs.getString("telefono");
                modelALU.addRow(alumnos1);
            }
            tablaalaumnos.setModel(modelALU);
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error...");
        }        
    }
    //////////// AÑADIR CALIFICAIONES
    public void AgCali(){
        String id_calificaion=id_cali.getText();
        String id_alumno=id_alu.getText();
        String cali_a=P1.getText();
        String cali_b=P2.getText();
        String cali_c=P3.getText();
             
        String op= (String)parciales.getSelectedItem();
        try{
            Connection Conexion = CON.conectar();
            java.sql.Statement ps=Conexion.createStatement();
            //inserta calificacion1
            if(op.equals("Parcial 1")){
                String sql = "insert into det_calificaciones (id_calificacion,cali_uno) values('"+id_calificaion+"','"+cali_a+"')";
                ps.execute(sql);
                Conexion.close();
                JOptionPane.showMessageDialog(null, "1er parcial registrado.");
            }
            //inserta calificacion2
            if(op.equals("Parcial 2")){
                String sql = "update det_calificaciones set cali_dos ='"+cali_b+"' where id_calificacion ='"+id_calificaion+"'";
                ps.execute(sql);
                Conexion.close();
                JOptionPane.showMessageDialog(null, "2do parcial registrado.");
            }
            //inserta calificacion3
            if(op.equals("Parcial 3")){
                String sql = "update det_calificaciones set cali_tres ='"+cali_c+"' where id_calificacion ='"+id_calificaion+"'";
                ps.execute(sql);
                Conexion.close();
                JOptionPane.showMessageDialog(null, "3er parcial registrado.");
            }    
        }catch(Exception e){
            System.out.println("Error al insertar");
        }
    }
    public void AgregarCali(){
        String calificacion=id_cal2.getText();
        String Grado=grado_grupo.getText();
        //String ID_a=ID_alumno.getText();
        //String Grado_Grupo=(String) horarios.getSelectedItem();
        String id=(String) idAlumnos.getSelectedItem(); 
        try{
            Connection Conexion = CON.conectar();
            java.sql.Statement st=Conexion.createStatement();
            String sql = "insert into calificaciones (id_calificacion,id_alumno,grado_grupo) values ('"+calificacion+"','"+id+"','"+Grado+"')";
            st.execute(sql);
            Conexion.close();
            JOptionPane.showMessageDialog(null, "Datos agregado.");
        }catch(Exception e){
            System.out.println("Error al insertar");
        }    
    }
    DefaultTableModel modeloCali;
    public void CalificacionF(){
        String gradofinal = Gradofinal.getText();
        //
        String sql ="select id_calificacion, id_alumno, grado_grupo, cali_final from Calificaciones where grado_grupo = '"+gradofinal+"'; ";
        try {
            Connection Conexion = CON.conectar();
            ps=CON.conectar().createStatement();
            rs = ps.executeQuery(sql);
            Object [] alumnoscali = new Object[4];
            modeloCali = (DefaultTableModel) TABLACALI.getModel();
            while(rs.next()){
                alumnoscali [0] = rs.getString("id_calificacion");
                alumnoscali [1] = rs.getString("id_alumno");
                alumnoscali [2] = rs.getString("grado_grupo");
                alumnoscali [3] = rs.getString("cali_final");
                modeloCali.addRow(alumnoscali);
            }
            TABLACALI.setModel(modeloCali);
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error...");
        }        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JTextField DOCENTE;
    private javax.swing.JTextField Gradofinal;
    private javax.swing.JComboBox IDXD;
    private javax.swing.JTextField P1;
    private javax.swing.JTextField P2;
    private javax.swing.JTextField P3;
    private javax.swing.JButton Salir;
    private javax.swing.JTable TABLACALI;
    private javax.swing.JButton activar3;
    private javax.swing.JTextField grado;
    private javax.swing.JTextField grado_grupo;
    private javax.swing.JComboBox idAlumnos;
    private javax.swing.JTextField id_alu;
    private javax.swing.JTextField id_cal2;
    private javax.swing.JTextField id_cali;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox parciales;
    private javax.swing.JTable tablaalaumnos;
    // End of variables declaration//GEN-END:variables
}
